# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-29 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_cargo', models.CharField(max_length=128, verbose_name='Descri\xe7\xe3o do cargo')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_hora', models.CharField(max_length=128, verbose_name='Descri\xe7\xe3o de configura\xe7\xe3o da hora')),
                ('hora_entrada_1', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada 1')),
                ('hora_saida_1', models.TimeField(blank=True, null=True, verbose_name='Hora de sa\xedda 1')),
                ('hora_entrada_2', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada 2')),
                ('hora_saida_2', models.TimeField(blank=True, null=True, verbose_name='Hora de sa\xedda 2')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ponto', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada 1')),
                ('ip_registro', models.CharField(blank=True, default=b'10.9.1.53', editable=False, max_length=20, null=True)),
                ('data_resgistro', models.DateField(auto_now_add=True, null=True, verbose_name='Data do registro')),
                ('juntificativa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome do funcion\xe1rio')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.Cargo', verbose_name='Cargo do funcion\xe1rio')),
                ('configuracao_hora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.ConfiguracaoHora', verbose_name='Configura\xe7\xe3o da hora')),
                ('funciorio_pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.Funcionario')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usu\xe1rio')),
            ],
        ),
        migrations.CreateModel(
            name='StatusPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_status', models.CharField(max_length=128, verbose_name='Descri\xe7\xe3o do status do ponto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoBatidaPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_ponto', models.CharField(max_length=128, verbose_name='Descri\xe7\xe3o da batida de ponto')),
            ],
        ),
        migrations.AddField(
            model_name='frequencia',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.Funcionario', verbose_name='Funcion\xe1rio'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='status_ponto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.StatusPonto', verbose_name='Status ponto'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='tipo_ponto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_frequencia.TipoBatidaPonto', verbose_name='Tipo ponto'),
        ),
    ]
