# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-29 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_frequencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='funciorio_pessoa',
            new_name='funcionario_pessoa',
        ),
    ]
